## 服务端口
#  server.port=8201
spring:
  application:
    name: CS223Project
  profiles:
    active: dev
  datasource:
    dynamic:
      primary: leader #default datasource
      strict: false
      datasource:
        leader:
          url: jdbc:postgresql://localhost:5432/leader
          username: postgres
          password: lyq990515
          driver-class-name: org.postgresql.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        follower1:
          url: jdbc:postgresql://localhost:5432/follower1
          username: postgres
          password: lyq990515
          driver-class-name: org.postgresql.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        follower2:
          url: jdbc:postgresql://localhost:5432/follower2
          username: postgres
          password: lyq990515
          driver-class-name: org.postgresql.Driver
          type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#
#logging:
#  config: classpath:logback-spring.xml